### ISSUE TITLE
default_scoped doesn't work in rails 4.0

### ISSUE THREAD

**Issue by TamarinEA** [collectiveidea/awesome_nested_set#443]
Hi.
`default_scoped` method In this row https://github.com/collectiveidea/awesome_nested_set/blob/e097e4ace1dcd523faeda44f553983e5cb5d8c1f/lib/awesome_nested_set/model.rb#L149 doesn't work in rails 4.0
```
NameError: undefined local variable or method `default_scoped' for #<Class:0x000000050af528>
# gems/activerecord-4.0.13/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
# gems/awesome_nested_set-3.3.1/lib/awesome_nested_set/model.rb:83:in `nested_set_scope'
# gems/awesome_nested_set-3.3.1/lib/awesome_nested_set/model.rb:154:in `nested_set_scope'
# gems/awesome_nested_set-3.3.1/lib/awesome_nested_set/model.rb:194:in `has_depth_column?'
# gems/awesome_nested_set-3.3.1/lib/awesome_nested_set/model.rb:213:in `set_depth!'
```

Please remove unsupported versions from gemspec.

**Comment by parndt** [comment]
Oh, thanks for letting us know @TamarinEA ! Looks like, luckily, this was part of #437 which hasn't been released as a gem yet. Are you using it from a git source?

@p8 FYI ^ no action required, just letting you know.

I agree, we should remove older versions of Rails from the supported list, and release the next version as 4.0.0

**Comment by TamarinEA** [comment]
> Are you using it from a git source?

No, but I was mistake with the github link. Method in version 3.3.1 https://github.com/collectiveidea/awesome_nested_set/blob/v3.3.1/lib/awesome_nested_set/model.rb#L83 .

**Comment by parndt** [comment]
Ohh - thanks @TamarinEA that is indeed a problem

**Comment by p8** [comment]
@parndt Thanks, for the heads up.
